theme: jekyll-theme-minimal
title: Anand Murugesan
description: research, teaching & other updates here {\scriptsize (photo credit: Tiziana Centofanti)}.
logo: /am_2021s.jpg
google_analytics: [UA-55493687-2] 

